name: Build
on: [push]

jobs:
  build_4_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 16
      - name: install dependencies
        run: yarn
      - name: build
        run: yarn package
      - uses: actions/upload-artifact@v2
        with:
          name: macos-app
          path: out/sneaky-uploader-darwin-x64/sneaky-uploader.app
  build_4_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 16
      - name: install dependencies
        run: yarn
      - name: build
        run: yarn package
      - uses: actions/upload-artifact@v2
        with:
          name: windows-app
          path: out/sneaky-uploader-win32-x64/sneaky-uploader.exe

